# Poxy configuration file for progression library
# See https://github.com/marzer/poxy for more information

name = 'progression'
author = 'Magpiny BO'
description = 'A header-only C++ progression library implementing arithmetic, geometric, and Fibonacci progressions'
github = 'Magpiny/cpp-dsa'
cpp = 17
theme='dark'
license = ['MIT', 'https://opensource.org/licenses/MIT']
twitter = 'SamuelWanjare'
dot = true
extra_files = ['README.md']
main_page = true

[sources]
paths = ['progression.hpp']

[warnings]
enabled         = true
treat_as_errors = false
undocumented    = true

[badges]
'C++20'       = [ 'badge-C++20.svg', 'https://en.cppreference.com/w/cpp/compiler_support' ]
'TOML v1.0.0' = [ 'badge-TOML.svg', 'https://toml.io/en/v1.0.0' ]
